export const FEM_COURSE_URLS = [ "https://frontendmasters.com/courses/javascript-projects/",
    "https://frontendmasters.com/courses/angular-fundamentals/",
    "https://frontendmasters.com/courses/advanced-algorithms/",
    "https://frontendmasters.com/courses/htmx/",
    "https://frontendmasters.com/courses/blazingly-fast-js/",
    "https://frontendmasters.com/courses/engineering-management/",
    "https://frontendmasters.com/courses/intro-management/",
    "https://frontendmasters.com/courses/tailwind-css/",
    "https://frontendmasters.com/courses/vite/",
    "https://frontendmasters.com/courses/enterprise-typescript/",
    "https://frontendmasters.com/courses/intermediate-typescript-v2/",
    "https://frontendmasters.com/courses/typescript-v4/",
    "https://frontendmasters.com/courses/openai-node/",
    "https://frontendmasters.com/courses/enterprise-devops/",
    "https://frontendmasters.com/courses/javascript-cpu-vm/",
    "https://frontendmasters.com/courses/css-projects/",
    "https://frontendmasters.com/courses/scratch/",
    "https://frontendmasters.com/courses/arduino-javascript/",
    "https://frontendmasters.com/courses/product-management/",
    "https://frontendmasters.com/courses/electron-v3/",
    "https://frontendmasters.com/courses/css-foundations/",
    "https://frontendmasters.com/courses/getting-a-job-v2/",
    "https://frontendmasters.com/courses/chat-apis/",
    "https://frontendmasters.com/courses/astro/",
    "https://frontendmasters.com/courses/node-js-v3/",
    "https://frontendmasters.com/courses/fullstack-app-next-v3/",
    "https://frontendmasters.com/courses/next-js-v3/",
    "https://frontendmasters.com/courses/go-basics/",
    "https://frontendmasters.com/courses/web-app-performance/",
    "https://frontendmasters.com/courses/css-layouts/",
    "https://frontendmasters.com/courses/chatgpt-api/",
    "https://frontendmasters.com/courses/device-web-apis/",
    "https://frontendmasters.com/courses/vanilla-js-apps/",
    "https://frontendmasters.com/courses/hard-parts-ui-dev/",
    "https://frontendmasters.com/courses/sveltekit/",
    "https://frontendmasters.com/courses/svelte-v2/",
    "https://frontendmasters.com/courses/web-dev-quiz/",
    "https://frontendmasters.com/courses/enterprise-ui-dev/",
    "https://frontendmasters.com/courses/design-systems-management/",
    "https://frontendmasters.com/courses/java/",
    "https://frontendmasters.com/courses/rust-ts-devs/",
    "https://frontendmasters.com/courses/fullstack-v3/",
    "https://frontendmasters.com/courses/algorithms-practice/",
    "https://frontendmasters.com/courses/devops/",
    "https://frontendmasters.com/courses/qwik/",
    "https://frontendmasters.com/courses/web-storage-apis/",
    "https://frontendmasters.com/courses/web-auth-apis/",
    "https://frontendmasters.com/courses/advanced-redux/",
    "https://frontendmasters.com/courses/react-performance/",
    "https://frontendmasters.com/courses/react-typescript-v2/",
    "https://frontendmasters.com/courses/background-javascript/",
    "https://frontendmasters.com/courses/reactivity-solidjs/",
    "https://frontendmasters.com/courses/vue-fundamentals/",
    "https://frontendmasters.com/courses/intermediate-react-v5/",
    "https://frontendmasters.com/courses/complete-react-v8/",
    "https://frontendmasters.com/courses/javascript-first-steps/",
    "https://frontendmasters.com/courses/api-design-nodejs-v4/",
    "https://frontendmasters.com/courses/vue-typescript/",
    "https://frontendmasters.com/courses/nuxt/",
    "https://frontendmasters.com/courses/sql/",
    "https://frontendmasters.com/courses/advanced-remix/",
    "https://frontendmasters.com/courses/remix/",
    "https://frontendmasters.com/courses/algorithms/",
    "https://frontendmasters.com/courses/intermediate-html-css/",
    "https://frontendmasters.com/courses/web-development-v3/",
    "https://frontendmasters.com/courses/tour-js-patterns/",
    "https://frontendmasters.com/courses/typescript-go-rust/",
    "https://frontendmasters.com/courses/firebase/",
    "https://frontendmasters.com/courses/design-process/",
    "https://frontendmasters.com/courses/freelancing/",
    "https://frontendmasters.com/courses/css-animations/",
    "https://frontendmasters.com/courses/flutter/",
    "https://frontendmasters.com/courses/android-kotlin/",
    "https://frontendmasters.com/courses/swift-ios/",
    "https://frontendmasters.com/courses/data-visualization/",
    "https://frontendmasters.com/courses/unity/",
    "https://frontendmasters.com/courses/web-components/",
    "https://frontendmasters.com/courses/fullstack-typescript/",
    "https://frontendmasters.com/courses/typescript-practice/",
    "https://frontendmasters.com/courses/figma/",
    "https://frontendmasters.com/courses/cypress/",
    "https://frontendmasters.com/courses/aws-v2/",
    "https://frontendmasters.com/courses/web3-smart-contracts/",
    "https://frontendmasters.com/courses/rapid-app-dev/",
    "https://frontendmasters.com/courses/rx-js/",
    "https://frontendmasters.com/courses/pwas/",
    "https://frontendmasters.com/courses/xstate-v2/",
    "https://frontendmasters.com/courses/getting-started-css/",
    "https://frontendmasters.com/courses/web-audio/",
    "https://frontendmasters.com/courses/ux-design-principles/",
    "https://frontendmasters.com/courses/css-variables/",
    "https://frontendmasters.com/courses/intermediate-react-native/",
    "https://frontendmasters.com/courses/css-grid-flexbox-v2/",
    "https://frontendmasters.com/courses/developer-productivity/",
    "https://frontendmasters.com/courses/realtime/",
    "https://frontendmasters.com/courses/intermediate-gatsby-v2/",
    "https://frontendmasters.com/courses/gatsby-v2/",
    "https://frontendmasters.com/courses/computer-science-v2/",
    "https://frontendmasters.com/courses/redux-fundamentals/",
    "https://frontendmasters.com/courses/accessibility-v2/",
    "https://frontendmasters.com/courses/rust/",
    "https://frontendmasters.com/courses/vim-fundamentals/",
    "https://frontendmasters.com/courses/web-assembly/",
    "https://frontendmasters.com/courses/dev-tools/",
    "https://frontendmasters.com/courses/web-perf/",
    "https://frontendmasters.com/courses/intro-deno/",
    "https://frontendmasters.com/courses/3d-webxr/",
    "https://frontendmasters.com/courses/production-next/",
    "https://frontendmasters.com/courses/production-vue/",
    "https://frontendmasters.com/courses/functional-first-steps/",
    "https://frontendmasters.com/courses/enterprise-patterns/",
    "https://frontendmasters.com/courses/production-angular/",
    "https://frontendmasters.com/courses/xstate-react/",
    "https://frontendmasters.com/courses/practical-python/",
    "https://frontendmasters.com/courses/databases/",
    "https://frontendmasters.com/courses/monorepos/",
    "https://frontendmasters.com/courses/vue-nuxt-apps/",
    "https://frontendmasters.com/courses/vue-3/",
    "https://frontendmasters.com/courses/d3/",
    "https://frontendmasters.com/courses/serverless-functions/",
    "https://frontendmasters.com/courses/linux-command-line/",
    "https://frontendmasters.com/courses/vuex/",
    "https://frontendmasters.com/courses/front-end-game/",
    "https://frontendmasters.com/courses/design-systems/",
    "https://frontendmasters.com/courses/react-native-v2/",
    "https://frontendmasters.com/courses/webgl-shaders/",
    "https://frontendmasters.com/courses/hardcore-js-patterns/",
    "https://frontendmasters.com/courses/hardcore-js-v2/",
    "https://frontendmasters.com/courses/practical-machine-learning/",
    "https://frontendmasters.com/courses/advanced-graphql-v2/",
    "https://frontendmasters.com/courses/jamstack/",
    "https://frontendmasters.com/courses/interviewing-frontend/",
    "https://frontendmasters.com/courses/complete-intro-containers/",
    "https://frontendmasters.com/courses/javascript-hard-parts-v2/",
    "https://frontendmasters.com/courses/client-graphql-react/",
    "https://frontendmasters.com/courses/server-graphql-nodejs/",
    "https://frontendmasters.com/courses/html-email-v2/",
    "https://frontendmasters.com/courses/programming-language/",
    "https://frontendmasters.com/courses/customize-vs-code/",
    "https://frontendmasters.com/courses/functional-js-fundamentals/",
    "https://frontendmasters.com/courses/advanced-css-layouts/",
    "https://frontendmasters.com/courses/javascript-accessibility/",
    "https://frontendmasters.com/courses/redux-mobx/",
    "https://frontendmasters.com/courses/service-workers/",
    "https://frontendmasters.com/courses/digging-into-node/",
    "https://frontendmasters.com/courses/ember-octane/",
    "https://frontendmasters.com/courses/getting-started-javascript-v2/",
    "https://frontendmasters.com/courses/functional-javascript-v3/",
    "https://frontendmasters.com/courses/servers-node-js/",
    "https://frontendmasters.com/courses/trees-and-graphs/",
    "https://frontendmasters.com/courses/intermediate-python/",
    "https://frontendmasters.com/courses/python/",
    "https://frontendmasters.com/courses/js-recent-parts/",
    "https://frontendmasters.com/courses/deep-javascript-v3/",
    "https://frontendmasters.com/courses/svg-essentials-animation/",
    "https://frontendmasters.com/courses/design-for-developers/",
    "https://frontendmasters.com/courses/angular-reactive/",
    "https://frontendmasters.com/courses/canvas-webgl/",
    "https://frontendmasters.com/courses/mongodb/",
    "https://frontendmasters.com/courses/object-oriented-js/",
    "https://frontendmasters.com/courses/advanced-elm/",
    "https://frontendmasters.com/courses/intro-elm/",
    "https://frontendmasters.com/courses/d3-js-custom-charts/",
    "https://frontendmasters.com/courses/d3-js-react/",
    "https://frontendmasters.com/courses/testing-practices-principles/",
    "https://frontendmasters.com/courses/responsive-typography-v2/",
    "https://frontendmasters.com/courses/data-structures-interviews/",
    "https://frontendmasters.com/courses/javascript-new-hard-parts/",
    "https://frontendmasters.com/courses/webpack-plugins/",
    "https://frontendmasters.com/courses/performance-webpack/",
    "https://frontendmasters.com/courses/webpack-fundamentals/",
    "https://frontendmasters.com/courses/practical-algorithms/",
    "https://frontendmasters.com/courses/serverless-aws/",
    "https://frontendmasters.com/courses/content-strategy/",
    "https://frontendmasters.com/courses/web-performance/",
    "https://frontendmasters.com/courses/git-in-depth/",
    "https://frontendmasters.com/courses/advanced-vue/",
    "https://frontendmasters.com/courses/visual-studio-code/",
    "https://frontendmasters.com/courses/web-security/",
    "https://frontendmasters.com/courses/advanced-async-js/",
    "https://frontendmasters.com/courses/testing-modular-front-end/",
    "https://frontendmasters.com/courses/leveldb-crypto/",
    "https://frontendmasters.com/courses/networking-streams/",
    "https://frontendmasters.com/courses/bash-vim-regex/",
    "https://frontendmasters.com/courses/linting-asts/",
    "https://frontendmasters.com/courses/modern-seo/",
    "https://frontendmasters.com/courses/sass/",
    "https://frontendmasters.com/courses/debugging-javascript/",
    "https://frontendmasters.com/courses/open-source/",
    "https://frontendmasters.com/courses/good-parts-javascript-web/",
    "https://frontendmasters.com/courses/rethinking-async-js/",
    "https://frontendmasters.com/courses/asynchronous-javascript/",
    "https://frontendmasters.com/courses/smacss/"]

export const FEM_DOWNLOADED_COURSE_URLS = FEM_COURSE_URLS

const FEM_BASE = 'frontendmasters.com'

export const FEM_ENDPOINT = `https://${FEM_BASE}`
export const FEM_API_ENDPOINT = `https://api.${FEM_BASE}/v1`
export const FEM_CAPTIONS_ENDPOINT = `https://captions.${FEM_BASE}`
export const PLAYLIST_EXT = 'm3u8'
export const CAPTION_EXT = 'vtt'
export const QUALITY_FORMAT = {
    2160: ['index_2160p_Q10_20mbps'],
    1440: ['index_1440p_Q10_9mbps'],
    1080: ['index_1080_Q10_7mbps', 'index_1080_Q8_7mbps'],
    720: ['index_720_Q8_5mbps'],
    360: ['index_360_Q8_2mbps']
}

export const FEM_COURSE_REG = /(:?https?:\/\/)?frontendmasters\.com\/courses\/([^/]+)/

export const SUPPORTED_FORMATS = [
    'mp4',
    'mkv'
]


export const USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
